name: hello-world
on: push
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r test-requirements.txt
      # Linting
      - run: pep8 ./hello-rest-api/
      - run: mypy ./hello_rest_api/
      - run: pylint ./hello_rest_api/
      # Unit tests
      - run: pytest ./hello-rest-api